import { render, screen, within } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { MemoryRouter, Route, Routes } from 'react-router-dom';
import { describe, expect, it, vi } from 'vitest';
import { AdminApiError, createAdminApi, type AdminApi, type AuditDetail, type MaintenanceState, type OperationalJob } from '../../api/adminApi';
import { AuthProvider } from '../../auth/AuthContext';
import { AuditDetailPage, AuditPage, OperationalJobPage, OperationalJobsPage, OperationsCachePage, OperationsHealthPage, OperationsMaintenancePage, OperationsPage } from './Operations';

const id='11111111-1111-4111-8111-111111111111';
const timestamp='2026-08-25T10:00:00Z';
const job:OperationalJob={id,status:'failed',createdAt:timestamp,startedAt:timestamp,completedAt:timestamp,durationMs:12,retryCount:1,lastError:'Safe failure summary',executionNode:'worker-1',jobType:'ingestion'};
const maintenance:MaintenanceState={enabled:false,message:null,updatedAt:timestamp,updatedBy:null,requestId:null,correlationId:null};
const audit:AuditDetail={id,timestamp,user:'admin@example.test',actor:'admin@example.test',action:'cache.clear',resource:'cache',result:'SUCCESS',durationMs:4,requestId:'request-1',correlationId:'correlation-1',metadata:{safe:'<img src=x onerror=alert(1)>'}};
function apiWith(overrides:Partial<AdminApi>={}):AdminApi{return{...createAdminApi(''),getOperations:vi.fn().mockResolvedValue({generatedAt:timestamp,service:'operations',status:'available',capabilities:['health','cache','maintenance','jobs','audit']}),getOperationsHealth:vi.fn().mockResolvedValue({generatedAt:timestamp,status:'healthy',checks:[]}),listCacheRegions:vi.fn().mockResolvedValue([]),getMaintenance:vi.fn().mockResolvedValue(maintenance),listOperationalJobs:vi.fn().mockResolvedValue({items:[],total:0,limit:50,offset:0}),getOperationalJob:vi.fn().mockResolvedValue(job),listAuditEntries:vi.fn().mockResolvedValue({items:[],total:0,limit:50,offset:0}),getAuditEntry:vi.fn().mockResolvedValue(audit),...overrides}}
const user={id:'admin',email:'admin@example.test',role:'administrator' as const};
function Frame({api,initial='/admin/operations',children}:{api:AdminApi;initial?:string;children:React.ReactNode}){return <MemoryRouter initialEntries={[initial]}><AuthProvider api={api} initialUser={user}><Routes><Route path="*" element={children}/></Routes></AuthProvider></MemoryRouter>}

describe('detailed Operations UI',()=>{
  it('advertises only backend capabilities',async()=>{render(<Frame api={apiWith({getOperations:vi.fn().mockResolvedValue({generatedAt:timestamp,service:'operations',status:'available',capabilities:['health','jobs']})})}><OperationsPage/></Frame>);expect(await screen.findByRole('link',{name:'Open Health'})).toHaveAttribute('href','/admin/operations/health');expect(screen.getByRole('link',{name:'Open Jobs'})).toBeInTheDocument();expect(screen.queryByRole('link',{name:'Open Cache'})).not.toBeInTheDocument()});

  it.each(['healthy','degraded','unhealthy','unknown'] as const)('renders %s health as successful diagnostics',async(status)=>{render(<Frame api={apiWith({getOperationsHealth:vi.fn().mockResolvedValue({generatedAt:timestamp,status,checks:[{name:'postgres',status,required:true,latencyMs:7,code:status==='healthy'?null:'dependency_unavailable',checkedAt:timestamp}]})})}><OperationsHealthPage/></Frame>);const overview=await screen.findByRole('heading',{name:'Overall health'});expect(overview.closest('section')).toHaveTextContent(status[0].toUpperCase()+status.slice(1));expect(screen.getByRole('heading',{name:'postgres'}).closest('section')).toHaveTextContent('7 ms')});

  it('renders unavailable cache metrics and confirms the exact region before mutation',async()=>{const clearCacheRegion=vi.fn().mockResolvedValue({success:true,requestId:'r',correlationId:'c'});render(<Frame api={apiWith({listCacheRegions:vi.fn().mockResolvedValue([{name:'assistant',entries:null,estimatedMemoryBytes:null,hitCount:2,missCount:1,hitRatio:null}]),clearCacheRegion})}><OperationsCachePage/></Frame>);const row=(await screen.findByRole('row',{name:/assistant/}));expect(within(row).getAllByText('Not available')).toHaveLength(3);await userEvent.click(within(row).getByRole('button',{name:'Clear assistant'}));expect(screen.getByRole('dialog')).toHaveTextContent('assistant');expect(clearCacheRegion).not.toHaveBeenCalled();await userEvent.click(screen.getByRole('button',{name:'Clear region'}));expect(clearCacheRegion).toHaveBeenCalledWith('assistant');expect(await screen.findByRole('status')).toHaveTextContent('assistant cache region cleared')});

  it('requires key confirmation and blocks another mutation after an ambiguous network outcome',async()=>{const invalidateCacheKey=vi.fn().mockRejectedValue(new AdminApiError('network'));render(<Frame api={apiWith({listCacheRegions:vi.fn().mockResolvedValue([{name:'assistant',entries:1,estimatedMemoryBytes:2,hitCount:3,missCount:4,hitRatio:.5}]),invalidateCacheKey})}><OperationsCachePage/></Frame>);await userEvent.selectOptions(await screen.findByLabelText('Region'),'assistant');await userEvent.type(screen.getByLabelText('Cache key'),'private-key');await userEvent.click(screen.getByRole('button',{name:'Review invalidation'}));expect(invalidateCacheKey).not.toHaveBeenCalled();await userEvent.click(screen.getByRole('button',{name:'Invalidate key'}));expect(await screen.findByRole('alert')).toHaveTextContent('outcome is unknown');expect(screen.getByRole('button',{name:'Clear all cache regions'})).toBeDisabled()});

  it('deliberately confirms maintenance and prevents duplicate submission',async()=>{let resolve!:(value:MaintenanceState)=>void;const updateMaintenance=vi.fn(()=>new Promise<MaintenanceState>((done)=>{resolve=done}));render(<Frame api={apiWith({updateMaintenance})}><OperationsMaintenancePage/></Frame>);await userEvent.type(await screen.findByLabelText('Maintenance message'),'Planned work');await userEvent.click(screen.getByRole('button',{name:'Review enable'}));expect(screen.getByRole('dialog')).toHaveTextContent('production-facing');await userEvent.click(screen.getByRole('button',{name:'Enable maintenance'}));expect(screen.getByRole('button',{name:'Working…'})).toBeDisabled();await userEvent.click(screen.getByRole('button',{name:'Working…'}));expect(updateMaintenance).toHaveBeenCalledOnce();expect(updateMaintenance).toHaveBeenCalledWith({enabled:true,message:'Planned work'});resolve({...maintenance,enabled:true,message:'Planned work'});expect(await screen.findByRole('status')).toHaveTextContent('Maintenance mode enabled')});

  it('uses server job filtering/pagination and renders safe detail only',async()=>{const listOperationalJobs=vi.fn().mockResolvedValue({items:[job],total:51,limit:50,offset:0});const api=apiWith({listOperationalJobs});render(<Frame api={api} initial="/admin/operations/jobs"><OperationalJobsPage/></Frame>);expect(await screen.findByText('Safe failure summary')).toBeInTheDocument();await userEvent.selectOptions(screen.getByLabelText('Status'),'failed');expect(await screen.findByText('Showing 1–50 of 51')).toBeInTheDocument();expect(listOperationalJobs).toHaveBeenLastCalledWith({limit:50,offset:0,status:'failed'},expect.any(AbortSignal));await userEvent.click(screen.getByRole('button',{name:'Next'}));expect(listOperationalJobs).toHaveBeenLastCalledWith({limit:50,offset:50,status:'failed'},expect.any(AbortSignal))});

  it('renders missing job and explicit permission failures safely',async()=>{render(<Frame api={apiWith({getOperationalJob:vi.fn().mockRejectedValue(new AdminApiError('not_found'))})} initial={`/admin/operations/jobs/${id}`}><OperationalJobPage/></Frame>);expect(await screen.findByRole('heading',{name:'Job not found'})).toBeInTheDocument();render(<Frame api={apiWith({getOperationsHealth:vi.fn().mockRejectedValue(new AdminApiError('forbidden'))})}><OperationsHealthPage/></Frame>);expect(await screen.findByRole('alert')).toHaveTextContent('do not have permission')});

  it('rejects inverted audit dates locally and keeps filters out of the request',async()=>{const listAuditEntries=vi.fn().mockResolvedValue({items:[],total:0,limit:50,offset:0});render(<Frame api={apiWith({listAuditEntries})} initial="/admin/operations/audit"><AuditPage/></Frame>);await screen.findByRole('heading',{name:'No audit entries'});await userEvent.type(screen.getByLabelText('Date from'),'2026-08-26T10:00');await userEvent.type(screen.getByLabelText('Date to'),'2026-08-25T10:00');await userEvent.click(screen.getByRole('button',{name:'Apply filters'}));expect(screen.getByRole('alert')).toHaveTextContent('Date from must be before');expect(listAuditEntries).toHaveBeenCalledOnce()});

  it('renders audit metadata as text data and handles a missing entry',async()=>{const {rerender}=render(<Frame api={apiWith()} initial={`/admin/operations/audit/${id}`}><AuditDetailPage/></Frame>);expect(await screen.findByText(/<img src=x/)).toBeInTheDocument();expect(document.querySelector('img')).toBeNull();rerender(<Frame api={apiWith({getAuditEntry:vi.fn().mockRejectedValue(new AdminApiError('not_found'))})} initial={`/admin/operations/audit/${id}`}><AuditDetailPage/></Frame>);expect(await screen.findByRole('heading',{name:'Audit entry not found'})).toBeInTheDocument()});
});
