import { act, render, screen, waitFor, within } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { MemoryRouter, Route, Routes, useLocation } from 'react-router-dom';
import { describe, expect, it, vi } from 'vitest';
import { AdminApiError, createAdminApi, type AdminApi, type AuditDetail, type MaintenanceState, type OperationalJob } from '../../api/adminApi';
import { AuthProvider } from '../../auth/AuthContext';
import { AuditDetailPage, AuditPage, OperationalJobPage, OperationalJobsPage, OperationsCachePage, OperationsHealthPage, OperationsMaintenancePage, OperationsPage } from './Operations';

const id='11111111-1111-4111-8111-111111111111';
const timestamp='2026-08-25T10:00:00Z';
const job:OperationalJob={id,status:'failed',createdAt:timestamp,startedAt:timestamp,completedAt:timestamp,durationMs:12,retryCount:1,lastError:'Safe failure summary',executionNode:'worker-1',jobType:'ingestion'};
const maintenance:MaintenanceState={enabled:false,message:null,updatedAt:timestamp,updatedBy:null,requestId:null,correlationId:null};
const audit:AuditDetail={id,timestamp,user:'admin@example.test',actor:'admin@example.test',action:'cache.clear',resource:'cache',result:'SUCCESS',durationMs:4,requestId:'request-1',correlationId:'correlation-1',metadata:{safe:'<img src=x onerror=alert(1)>'}};
function apiWith(overrides:Partial<AdminApi>={}):AdminApi{return{...createAdminApi(''),getOperations:vi.fn().mockResolvedValue({generatedAt:timestamp,service:'operations',status:'available',capabilities:['health','cache','maintenance','jobs','audit']}),getOperationsHealth:vi.fn().mockResolvedValue({generatedAt:timestamp,status:'healthy',checks:[]}),listCacheRegions:vi.fn().mockResolvedValue([]),getMaintenance:vi.fn().mockResolvedValue(maintenance),listOperationalJobs:vi.fn().mockResolvedValue({items:[],total:0,limit:50,offset:0}),getOperationalJob:vi.fn().mockResolvedValue(job),listAuditEntries:vi.fn().mockResolvedValue({items:[],total:0,limit:50,offset:0}),getAuditEntry:vi.fn().mockResolvedValue(audit),...overrides}}
const user={id:'admin',email:'admin@example.test',role:'administrator' as const};
function Frame({api,initial='/admin/operations',children}:{api:AdminApi;initial?:string;children:React.ReactNode}){return <MemoryRouter initialEntries={[initial]}><AuthProvider api={api} initialUser={user}><Routes><Route path="*" element={children}/></Routes></AuthProvider></MemoryRouter>}
function deferred<T>(){let resolve!:(value:T)=>void,reject!:(reason?:unknown)=>void;const promise=new Promise<T>((yes,no)=>{resolve=yes;reject=no});return{promise,resolve,reject}}
function LocationSearch(){return <output data-testid="location-search">{useLocation().search}</output>}

describe('detailed Operations UI',()=>{
  it('advertises only backend capabilities',async()=>{render(<Frame api={apiWith({getOperations:vi.fn().mockResolvedValue({generatedAt:timestamp,service:'operations',status:'available',capabilities:['health','jobs']})})}><OperationsPage/></Frame>);expect(await screen.findByRole('link',{name:'Open Health'})).toHaveAttribute('href','/admin/operations/health');expect(screen.getByRole('link',{name:'Open Jobs'})).toBeInTheDocument();expect(screen.queryByRole('link',{name:'Open Cache'})).not.toBeInTheDocument()});

  it.each(['healthy','degraded','unhealthy','unknown'] as const)('renders %s health as successful diagnostics',async(status)=>{render(<Frame api={apiWith({getOperationsHealth:vi.fn().mockResolvedValue({generatedAt:timestamp,status,checks:[{name:'postgres',status,required:true,latencyMs:7,code:status==='healthy'?null:'dependency_unavailable',checkedAt:timestamp}]})})}><OperationsHealthPage/></Frame>);const overview=await screen.findByRole('heading',{name:'Overall health'});expect(overview.closest('section')).toHaveTextContent(status[0].toUpperCase()+status.slice(1));expect(screen.getByRole('heading',{name:'postgres'}).closest('section')).toHaveTextContent('7 ms')});

  it('renders a safe invalid-response failure without invented health state',async()=>{render(<Frame api={apiWith({getOperationsHealth:vi.fn().mockRejectedValue(new AdminApiError('invalid_response'))})}><OperationsHealthPage/></Frame>);expect(await screen.findByRole('alert')).toHaveTextContent('invalid response');expect(screen.queryByRole('heading',{name:'Overall health'})).not.toBeInTheDocument();expect(screen.queryByText('Healthy')).not.toBeInTheDocument()});

  it('renders unavailable cache metrics and confirms the exact region before mutation',async()=>{const clearCacheRegion=vi.fn().mockResolvedValue({success:true,requestId:'r',correlationId:'c'});render(<Frame api={apiWith({listCacheRegions:vi.fn().mockResolvedValue([{name:'assistant',entries:null,estimatedMemoryBytes:null,hitCount:2,missCount:1,hitRatio:null}]),clearCacheRegion})}><OperationsCachePage/></Frame>);const row=(await screen.findByRole('row',{name:/assistant/}));expect(within(row).getAllByText('Not available')).toHaveLength(3);await userEvent.click(within(row).getByRole('button',{name:'Clear assistant'}));expect(screen.getByRole('dialog')).toHaveTextContent('assistant');expect(clearCacheRegion).not.toHaveBeenCalled();await userEvent.click(screen.getByRole('button',{name:'Clear region'}));expect(clearCacheRegion).toHaveBeenCalledWith('assistant');expect(await screen.findByRole('status')).toHaveTextContent('assistant cache region cleared')});

  it('requires key confirmation and blocks another mutation after an ambiguous network outcome',async()=>{const invalidateCacheKey=vi.fn().mockRejectedValue(new AdminApiError('network'));render(<Frame api={apiWith({listCacheRegions:vi.fn().mockResolvedValue([{name:'assistant',entries:1,estimatedMemoryBytes:2,hitCount:3,missCount:4,hitRatio:.5}]),invalidateCacheKey})}><OperationsCachePage/></Frame>);await userEvent.selectOptions(await screen.findByLabelText('Region'),'assistant');await userEvent.type(screen.getByLabelText('Cache key'),'private-key');await userEvent.click(screen.getByRole('button',{name:'Review invalidation'}));expect(invalidateCacheKey).not.toHaveBeenCalled();await userEvent.click(screen.getByRole('button',{name:'Invalidate key'}));expect(await screen.findByRole('alert')).toHaveTextContent('outcome is unknown');expect(screen.getByRole('button',{name:'Clear all cache regions'})).toBeDisabled()});

  it('confirms clear-all scope, prevents duplicates, and refreshes authoritative cache state',async()=>{const request=deferred<{success:true;requestId:string;correlationId:string}>();const clearCache=vi.fn(()=>request.promise);const listCacheRegions=vi.fn().mockResolvedValue([{name:'assistant',entries:1,estimatedMemoryBytes:null,hitCount:null,missCount:null,hitRatio:null}]);render(<Frame api={apiWith({listCacheRegions,clearCache})}><OperationsCachePage/></Frame>);await screen.findByRole('row',{name:/assistant/});await userEvent.click(screen.getByRole('button',{name:'Clear all cache regions'}));expect(screen.getByRole('dialog')).toHaveTextContent('all registered cache regions');expect(clearCache).not.toHaveBeenCalled();await userEvent.click(screen.getByRole('button',{name:'Clear all regions'}));expect(screen.getByRole('button',{name:'Working…'})).toBeDisabled();await userEvent.click(screen.getByRole('button',{name:'Working…'}));expect(clearCache).toHaveBeenCalledOnce();await act(async()=>request.resolve({success:true,requestId:'r',correlationId:'c'}));expect(await screen.findByRole('status')).toHaveTextContent('All cache regions cleared');await waitFor(()=>expect(listCacheRegions).toHaveBeenCalledTimes(2))});

  it('retains cache state and permits deliberate retry after a definitive rejection',async()=>{const clearCache=vi.fn().mockRejectedValueOnce(new AdminApiError('server')).mockResolvedValueOnce({success:true,requestId:'r',correlationId:'c'});render(<Frame api={apiWith({listCacheRegions:vi.fn().mockResolvedValue([{name:'assistant',entries:1,estimatedMemoryBytes:null,hitCount:null,missCount:null,hitRatio:null}]),clearCache})}><OperationsCachePage/></Frame>);await screen.findByRole('row',{name:/assistant/});await userEvent.click(screen.getByRole('button',{name:'Clear all cache regions'}));await userEvent.click(screen.getByRole('button',{name:'Clear all regions'}));expect(await screen.findByRole('alert')).toHaveTextContent('backend could not complete');expect(screen.getByRole('row',{name:/assistant/})).toBeInTheDocument();expect(screen.queryByRole('status')).not.toBeInTheDocument();await userEvent.click(screen.getByRole('button',{name:'Clear all regions'}));expect(clearCache).toHaveBeenCalledTimes(2);expect(await screen.findByRole('status')).toHaveTextContent('All cache regions cleared')});

  it('presents cache mutation permission denial as definitive, not ambiguous',async()=>{render(<Frame api={apiWith({listCacheRegions:vi.fn().mockResolvedValue([{name:'assistant',entries:1,estimatedMemoryBytes:null,hitCount:null,missCount:null,hitRatio:null}]),clearCache:vi.fn().mockRejectedValue(new AdminApiError('forbidden'))})}><OperationsCachePage/></Frame>);await screen.findByRole('row',{name:/assistant/});await userEvent.click(screen.getByRole('button',{name:'Clear all cache regions'}));await userEvent.click(screen.getByRole('button',{name:'Clear all regions'}));expect(await screen.findByRole('alert')).toHaveTextContent('do not have permission');expect(screen.queryByText(/outcome is unknown/)).not.toBeInTheDocument();expect(screen.queryByRole('status')).not.toBeInTheDocument()});

  it('deliberately confirms maintenance and prevents duplicate submission',async()=>{let resolve!:(value:MaintenanceState)=>void;const updateMaintenance=vi.fn(()=>new Promise<MaintenanceState>((done)=>{resolve=done}));render(<Frame api={apiWith({updateMaintenance})}><OperationsMaintenancePage/></Frame>);await userEvent.type(await screen.findByLabelText('Maintenance message'),'Planned work');await userEvent.click(screen.getByRole('button',{name:'Review enable'}));expect(screen.getByRole('dialog')).toHaveTextContent('production-facing');await userEvent.click(screen.getByRole('button',{name:'Enable maintenance'}));expect(screen.getByRole('button',{name:'Working…'})).toBeDisabled();await userEvent.click(screen.getByRole('button',{name:'Working…'}));expect(updateMaintenance).toHaveBeenCalledOnce();expect(updateMaintenance).toHaveBeenCalledWith({enabled:true,message:'Planned work'});resolve({...maintenance,enabled:true,message:'Planned work'});expect(await screen.findByRole('status')).toHaveTextContent('Maintenance mode enabled')});

  it('blocks maintenance changes after an ambiguous failure until refresh succeeds',async()=>{const refreshed=deferred<MaintenanceState>();const getMaintenance=vi.fn().mockResolvedValueOnce(maintenance).mockImplementationOnce(()=>refreshed.promise);render(<Frame api={apiWith({getMaintenance,updateMaintenance:vi.fn().mockRejectedValue(new AdminApiError('network'))})}><OperationsMaintenancePage/></Frame>);await userEvent.click(await screen.findByRole('button',{name:'Review enable'}));await userEvent.click(screen.getByRole('button',{name:'Enable maintenance'}));expect(await screen.findByRole('alert')).toHaveTextContent('may have changed');expect(screen.getByRole('button',{name:'Review enable'})).toBeDisabled();await userEvent.click(screen.getByRole('button',{name:'Refresh state'}));expect(screen.getByRole('button',{name:'Review enable'})).toBeDisabled();await act(async()=>refreshed.resolve(maintenance));await waitFor(()=>expect(screen.queryByText(/may have changed/)).not.toBeInTheDocument());expect(screen.getByRole('button',{name:'Review enable'})).toBeEnabled();expect(getMaintenance).toHaveBeenCalledTimes(2)});

  it.each([['backend rejection','server','backend could not complete'],['permission denial','forbidden','do not have permission']] as const)('does not claim maintenance changed after %s',async(_scenario,kind,message)=>{render(<Frame api={apiWith({updateMaintenance:vi.fn().mockRejectedValue(new AdminApiError(kind))})}><OperationsMaintenancePage/></Frame>);await userEvent.click(await screen.findByRole('button',{name:'Review enable'}));await userEvent.click(screen.getByRole('button',{name:'Enable maintenance'}));expect(await screen.findByRole('alert')).toHaveTextContent(message);expect(screen.queryByRole('status')).not.toBeInTheDocument();expect(screen.queryByText(/may have changed/)).not.toBeInTheDocument();expect(screen.getByRole('dialog')).toBeInTheDocument()});

  it('uses server job filtering/pagination and renders safe detail only',async()=>{const listOperationalJobs=vi.fn().mockResolvedValue({items:[job],total:51,limit:50,offset:0});const api=apiWith({listOperationalJobs});render(<Frame api={api} initial="/admin/operations/jobs"><OperationalJobsPage/></Frame>);expect(await screen.findByText('Safe failure summary')).toBeInTheDocument();await userEvent.selectOptions(screen.getByLabelText('Status'),'failed');expect(await screen.findByText('Showing 1–50 of 51')).toBeInTheDocument();expect(listOperationalJobs).toHaveBeenLastCalledWith({limit:50,offset:0,status:'failed'},expect.any(AbortSignal));await userEvent.click(screen.getByRole('button',{name:'Next'}));expect(listOperationalJobs).toHaveBeenLastCalledWith({limit:50,offset:50,status:'failed'},expect.any(AbortSignal))});

  it('renders missing job and explicit permission failures safely',async()=>{render(<Frame api={apiWith({getOperationalJob:vi.fn().mockRejectedValue(new AdminApiError('not_found'))})} initial={`/admin/operations/jobs/${id}`}><OperationalJobPage/></Frame>);expect(await screen.findByRole('heading',{name:'Job not found'})).toBeInTheDocument();render(<Frame api={apiWith({getOperationsHealth:vi.fn().mockRejectedValue(new AdminApiError('forbidden'))})}><OperationsHealthPage/></Frame>);expect(await screen.findByRole('alert')).toHaveTextContent('do not have permission')});

  it('renders every supported operational job detail field',async()=>{render(<Frame api={apiWith()} initial={`/admin/operations/jobs/${id}`}><OperationalJobPage/></Frame>);const details=(await screen.findByText(id)).closest('section')!;expect(details).toHaveTextContent('Failed');expect(details).toHaveTextContent('ingestion');expect(details).toHaveTextContent('Created');expect(details).toHaveTextContent('Started');expect(details).toHaveTextContent('Completed');expect(details).toHaveTextContent('12 ms');expect(details).toHaveTextContent('Retry count1');expect(details).toHaveTextContent('worker-1');expect(details).toHaveTextContent('Safe failure summary')});

  it('rejects inverted audit dates locally and keeps filters out of the request',async()=>{const listAuditEntries=vi.fn().mockResolvedValue({items:[],total:0,limit:50,offset:0});render(<Frame api={apiWith({listAuditEntries})} initial="/admin/operations/audit"><AuditPage/></Frame>);await screen.findByRole('heading',{name:'No audit entries'});await userEvent.type(screen.getByLabelText('Date from'),'2026-08-26T10:00');await userEvent.type(screen.getByLabelText('Date to'),'2026-08-25T10:00');await userEvent.click(screen.getByRole('button',{name:'Apply filters'}));expect(screen.getByRole('alert')).toHaveTextContent('Date from must be before');expect(listAuditEntries).toHaveBeenCalledOnce()});

  it('applies valid audit filters through the URL and resets the server offset',async()=>{const listAuditEntries=vi.fn().mockResolvedValue({items:[],total:0,limit:50,offset:0});render(<Frame api={apiWith({listAuditEntries})} initial="/admin/operations/audit?offset=50"><><AuditPage/><LocationSearch/></></Frame>);await screen.findByRole('heading',{name:'No audit entries'});await userEvent.type(screen.getByLabelText('User'),'admin@example.test');await userEvent.type(screen.getByLabelText('Action'),'cache.clear');await userEvent.type(screen.getByLabelText('Resource'),'cache');await userEvent.selectOptions(screen.getByLabelText('Result'),'SUCCESS');await userEvent.type(screen.getByLabelText('Date from'),'2026-08-25T09:00');await userEvent.type(screen.getByLabelText('Date to'),'2026-08-25T10:00');await userEvent.click(screen.getByRole('button',{name:'Apply filters'}));await waitFor(()=>expect(listAuditEntries).toHaveBeenLastCalledWith(expect.objectContaining({limit:50,offset:0,user:'admin@example.test',action:'cache.clear',resource:'cache',result:'SUCCESS',dateFrom:new Date('2026-08-25T09:00').toISOString(),dateTo:new Date('2026-08-25T10:00').toISOString()}),expect.any(AbortSignal)));const search=screen.getByTestId('location-search').textContent??'';expect(search).toContain('user=admin%40example.test');expect(search).toContain('action=cache.clear');expect(search).toContain('result=SUCCESS');expect(search).not.toContain('offset=')});

  it('pages audit results through authoritative server offsets',async()=>{const listAuditEntries=vi.fn().mockImplementation(async(options)=>({items:[audit],total:101,limit:50,offset:options?.offset??0}));render(<Frame api={apiWith({listAuditEntries})} initial="/admin/operations/audit"><><AuditPage/><LocationSearch/></></Frame>);await screen.findByText('cache.clear');await userEvent.click(screen.getByRole('button',{name:'Next'}));await waitFor(()=>expect(listAuditEntries).toHaveBeenLastCalledWith(expect.objectContaining({offset:50}),expect.any(AbortSignal)));expect(screen.getByTestId('location-search')).toHaveTextContent('offset=50');await userEvent.click(screen.getByRole('button',{name:'Previous'}));await waitFor(()=>expect(listAuditEntries).toHaveBeenLastCalledWith(expect.objectContaining({offset:0}),expect.any(AbortSignal)));expect(screen.getByTestId('location-search')).not.toHaveTextContent('offset=')});

  it('renders audit metadata as text data and handles a missing entry',async()=>{const {rerender}=render(<Frame api={apiWith()} initial={`/admin/operations/audit/${id}`}><AuditDetailPage/></Frame>);expect(await screen.findByText(/<img src=x/)).toBeInTheDocument();expect(document.querySelector('img')).toBeNull();rerender(<Frame api={apiWith({getAuditEntry:vi.fn().mockRejectedValue(new AdminApiError('not_found'))})} initial={`/admin/operations/audit/${id}`}><AuditDetailPage/></Frame>);expect(await screen.findByRole('heading',{name:'Audit entry not found'})).toBeInTheDocument()});

  it('renders populated audit detail fields',async()=>{render(<Frame api={apiWith()} initial={`/admin/operations/audit/${id}`}><AuditDetailPage/></Frame>);const details=(await screen.findByText('cache.clear')).closest('section')!;expect(details).toHaveTextContent('Success');expect(details).toHaveTextContent('admin@example.test');expect(details).toHaveTextContent('cache');expect(details).toHaveTextContent('4 ms');expect(details).toHaveTextContent('request-1');expect(details).toHaveTextContent('correlation-1');expect(details).toHaveTextContent('Metadata');expect(details).toHaveTextContent('<img src=x onerror=alert(1)>')});
});
